// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.mjs";
import * as Utils from "../../utils/Utils.mjs";
import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import IconComponentModuleScss from "./IconComponent.module.scss";

var styles = IconComponentModuleScss;

function IconComponent(props) {
  var props$1 = props.props;
  var props$2 = props$1 !== undefined ? props$1 : ({});
  var className = Utils.getClassNameFromProps(props$2);
  var filteredProps = Utils.filterProps(props$2);
  var newrecord = Caml_obj.obj_dup(filteredProps);
  return React.createElement("div", (newrecord.className = Cx.cx([
                    styles.icon,
                    className
                  ]), newrecord), props.children);
}

var make = IconComponent;

export {
  make ,
}
/* styles Not a pure module */
