// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.mjs";
import * as React from "react";
import IconComponentModuleScss from "./IconComponent.module.scss";

var styles = IconComponentModuleScss;

function IconComponent(props) {
  var className = props.className;
  var className$1 = className !== undefined ? className : "";
  return React.createElement("div", {
              className: Cx.cx([
                    styles.icon,
                    className$1
                  ])
            }, props.children);
}

var make = IconComponent;

export {
  make ,
}
/* styles Not a pure module */
