// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IconComponent from "../../IconComponent/IconComponent.mjs";
import IconArrowTriangleDownFillModuleScss from "./IconArrowTriangleDownFill.module.scss";

function IconArrowTriangleDownFill(props) {
  var className = props.className;
  var style = props.style;
  var style$1 = style !== undefined ? style : ({});
  var className$1 = className !== undefined ? className : "";
  return React.createElement(IconComponent.make, {
              children: React.createElement("svg", {
                    fill: "none",
                    viewBox: "0 0 16 16",
                    xmlns: "http://www.w3.org/2000/svg"
                  }, React.createElement("path", {
                        d: "M13 6.5L8 11.5L3 6.5L13 6.5Z",
                        fill: "currentColor"
                      })),
              style: style$1,
              className: className$1
            });
}

var make = IconArrowTriangleDownFill;

export {
  make ,
}
/*  Not a pure module */
