// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.mjs";
import * as React from "react";
import ButtonComponentModuleScss from "./ButtonComponent.module.scss";

var styles = ButtonComponentModuleScss;

function ButtonComponent(props) {
  return React.createElement("button", {
              className: Cx.cx([styles.root]),
              onClick: props.onClick
            }, props.children);
}

var make = ButtonComponent;

export {
  make ,
}
/* styles Not a pure module */
