// Generated by ReScript, PLEASE EDIT WITH CARE


var Req = {};

var Res = {};

var GetServerSideProps = {
  Req: Req,
  Res: Res
};

var GetStaticProps = {};

var GetStaticPaths = {};

var Link = {};

var Events = {};

var Router = {
  Events: Events
};

var Head = {};

var $$Error = {};

var Dynamic = {};

var MouseExtended = {};

export {
  GetServerSideProps ,
  GetStaticProps ,
  GetStaticPaths ,
  Link ,
  Router ,
  Head ,
  $$Error ,
  Dynamic ,
  MouseExtended ,
}
/* No side effect */
