// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IconComponent from "../../IconComponent/IconComponent.mjs";
import IconPencilModuleScss from "./IconPencil.module.scss";

function IconPencil(props) {
  var props$1 = props.props;
  var props$2 = props$1 !== undefined ? props$1 : ({});
  return React.createElement(IconComponent.make, {
              children: React.createElement("svg", {
                    fill: "none",
                    viewBox: "0 0 16 16",
                    xmlns: "http://www.w3.org/2000/svg"
                  }, React.createElement("path", {
                        d: "M14.5553 3.59195C15.1482 2.99901 15.1482 2.03765 14.5553 1.44471C13.9623 0.851764 13.001 0.851764 12.4081 1.44471L11.3166 2.53614C11.2376 2.6152 11.2376 2.74338 11.3166 2.82244L13.1776 4.68338C13.2566 4.76244 13.3848 4.76244 13.4639 4.68338L14.5553 3.59195Z",
                        fill: "currentColor"
                      }), React.createElement("path", {
                        d: "M12.1039 6.0433C12.183 5.96424 12.183 5.83606 12.1039 5.757L10.243 3.89605C10.1639 3.817 10.0358 3.817 9.95671 3.89605L2.41846 11.4343C2.37147 11.4813 2.33419 11.5371 2.30875 11.5985L1.01598 14.7195C0.946959 14.8861 1.11386 15.053 1.28049 14.984L4.4015 13.6913C4.46291 13.6658 4.5187 13.6285 4.5657 13.5815L12.1039 6.0433Z",
                        fill: "currentColor"
                      })),
              props: props$2
            });
}

var make = IconPencil;

export {
  make ,
}
/*  Not a pure module */
