// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function getClassNameFromProps(props) {
  var c = props.className;
  if (c !== undefined) {
    return c;
  } else {
    return "";
  }
}

function filterProps(props) {
  var newrecord = Caml_obj.obj_dup(props);
  newrecord.className = undefined;
  return newrecord;
}

export {
  getClassNameFromProps ,
  filterProps ,
}
/* No side effect */
