// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IconComponent from "../../IconComponent/IconComponent.mjs";
import IconExclamationMarkTriangleFillModuleScss from "./IconExclamationMarkTriangleFill.module.scss";

function IconExclamationMarkTriangleFill(props) {
  var props$1 = props.props;
  var props$2 = props$1 !== undefined ? props$1 : ({});
  return React.createElement(IconComponent.make, {
              children: React.createElement("svg", {
                    fill: "none",
                    viewBox: "0 0 16 16",
                    xmlns: "http://www.w3.org/2000/svg"
                  }, React.createElement("path", {
                        clipRule: "evenodd",
                        d: "M7.38989 1.62968C6.94465 1.82792 6.60361 2.41861 5.92153 3.6L1.4182 11.4C0.736128 12.5814 0.39509 13.1721 0.446035 13.6568C0.490472 14.0796 0.712216 14.4637 1.05614 14.7135C1.45044 15 2.13251 15 3.49667 15H12.5033C13.8675 15 14.5496 15 14.9439 14.7135C15.2878 14.4637 15.5095 14.0796 15.554 13.6568C15.6049 13.1721 15.2639 12.5814 14.5818 11.4L10.0785 3.6C9.39638 2.41861 9.05535 1.82792 8.6101 1.62968C8.22174 1.45677 7.77825 1.45677 7.38989 1.62968ZM8 5C7.31363 5 6.52246 5.2246 6.60995 6.0995L6.90995 9.0995C6.96736 9.67359 7.4588 10 8 10C8.54119 10 9.03264 9.67359 9.09005 9.0995L9.39005 6.0995C9.47754 5.2246 8.68637 5 8 5ZM7 12C7 11.4477 7.44771 11 8 11C8.55228 11 9 11.4477 9 12C9 12.5523 8.55228 13 8 13C7.44771 13 7 12.5523 7 12Z",
                        fill: "currentColor",
                        fillRule: "evenodd"
                      })),
              props: props$2
            });
}

var make = IconExclamationMarkTriangleFill;

export {
  make ,
}
/*  Not a pure module */
