// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "./layouts/MainLayout.mjs";
import * as Router from "next/router";

function $$default(props) {
  var router = Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  var match = router.route;
  switch (match) {
    case "/" :
    case "/buttons" :
        break;
    case "/examples" :
        return React.createElement(MainLayout.make, {
                    children: null
                  }, React.createElement("h1", undefined, "Examples Section"), React.createElement("div", undefined, content));
    default:
      return React.createElement(MainLayout.make, {
                  children: content
                });
  }
  return React.createElement(MainLayout.make, {
              children: null
            }, React.createElement("h1", undefined, "Buttons"), React.createElement("div", undefined, content));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
