// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CheckboxComponent from "./components/CheckboxComponent/CheckboxComponent.mjs";

function $$default(param) {
  var c = function (param) {
    
  };
  return React.createElement("div", undefined, React.createElement(CheckboxComponent.make, {
                  type_: /* M */0,
                  updateModelValue: c,
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  type_: /* S */1,
                  updateModelValue: c,
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  disabled: true,
                  updateModelValue: c,
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  isError: true,
                  updateModelValue: c,
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  modelValue: /* True */0,
                  disabled: true,
                  isError: true,
                  updateModelValue: c,
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  modelValue: /* Parted */2,
                  mode: /* Parted */1,
                  updateModelValue: c,
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  type_: /* M */0,
                  updateModelValue: c,
                  children: "Test text",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  type_: /* S */1,
                  updateModelValue: c,
                  children: "Small test text",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  disabled: true,
                  updateModelValue: c,
                  children: "Disabled test text",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  isError: true,
                  updateModelValue: c,
                  children: "Errored test text",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  modelValue: /* True */0,
                  disabled: true,
                  updateModelValue: c,
                  children: "Disabled checked test text",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(CheckboxComponent.make, {
                  modelValue: /* Parted */2,
                  mode: /* Parted */1,
                  updateModelValue: c,
                  children: "Parted value test text",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
