// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CheckboxComponent from "./components/CheckboxComponent/CheckboxComponent.mjs";

function $$default(param) {
  var c = function (param) {
    
  };
  return React.createElement("div", undefined, React.createElement(CheckboxComponent.make, {
                  type_: /* M */0,
                  updateModelValue: c,
                  children: "Тестовый текст"
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
