// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Icon4A from "./components/icons/Icon4A/Icon4A.mjs";
import * as IconPencil from "./components/icons/IconPencil/IconPencil.mjs";
import * as IconDocOnDoc from "./components/icons/IconDocOnDoc/IconDocOnDoc.mjs";
import * as IconCheckmark from "./components/icons/IconCheckmark/IconCheckmark.mjs";
import * as IconMinusLarge from "./components/icons/IconMinusLarge/IconMinusLarge.mjs";
import * as IconArrowTriangleDownFill from "./components/icons/IconArrowTriangleDownFill/IconArrowTriangleDownFill.mjs";

function $$default(param) {
  return React.createElement("div", undefined, React.createElement(Icon4A.make, {
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(IconArrowTriangleDownFill.make, {
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(IconCheckmark.make, {
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(IconDocOnDoc.make, {
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(IconMinusLarge.make, {
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(IconPencil.make, {
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
