// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$P(props) {
  return React.createElement("p", undefined, props.children);
}

function $$default(param) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "What is this about?"), React.createElement(Index$P, {
                  children: " This is a simple template for a Next\r\n      project using ReScript"
                }), React.createElement("h2", undefined, "Quick Start"), React.createElement("pre", undefined, "git clone https://github.com/rescript-nextjs-template.git my-project\r\ncd my-project\r\nrm -rf .git"));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
