// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Icon4A from "./components/icons/Icon4A/Icon4A.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ButtonComponent from "./components/ButtonComponent/ButtonComponent.mjs";
import * as IconArrowTriangleDownFill from "./components/icons/IconArrowTriangleDownFill/IconArrowTriangleDownFill.mjs";

function $$default(param) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  return React.createElement("div", undefined, React.createElement(ButtonComponent.make, {
                  value: "default count is " + String(count) + "",
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginTop: "16px",
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "Secondary count is " + String(count) + "",
                  typeColor: /* Secondary */1,
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "Tertiary count is " + String(count) + "",
                  typeColor: /* Tertiary */2,
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "Large count is " + String(count) + "",
                  typeSize: /* L */0,
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "Small count is " + String(count) + "",
                  typeSize: /* S */1,
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "Disabled count is " + String(count) + "",
                  disabled: true,
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "forceActive is " + String(count) + "",
                  forceActive: true,
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  type_: "text",
                  value: "Hidden div count is " + String(count) + "",
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "icon count is " + String(count) + "",
                  iconWithTextSlot: Caml_option.some(React.createElement(Icon4A.make, {})),
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "icon count is " + String(count) + "",
                  iconSingleSlot: Caml_option.some(React.createElement(Icon4A.make, {})),
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }), React.createElement(ButtonComponent.make, {
                  value: "icon count is " + String(count) + "",
                  iconDouble1Slot: Caml_option.some(React.createElement(Icon4A.make, {})),
                  iconDouble2Slot: Caml_option.some(React.createElement(IconArrowTriangleDownFill.make, {})),
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  style: {
                    marginBottom: "16px"
                  }
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
