// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ButtonComponent from "./components/ButtonComponent/ButtonComponent.mjs";

function Index$P(props) {
  return React.createElement("p", undefined, props.children);
}

function $$default(param) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement("div", undefined, React.createElement("h1", undefined, "What is this about?"), React.createElement(Index$P, {
                  children: " This is a simple template for a Next\r\n      project using ReScript"
                }), React.createElement(ButtonComponent.make, {
                  onClick: (function (param) {
                      Curry._1(setCount, (function (count) {
                              return count + 1 | 0;
                            }));
                    }),
                  children: "count is " + String(match[0]) + ""
                }), React.createElement("h2", undefined, "Quick Start"), React.createElement("pre", undefined, "git clone https://github.com/rescript-nextjs-template.git my-project\r\ncd my-project\r\nrm -rf .git"));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
