// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IconPencil from "./components/icons/IconPencil/IconPencil.mjs";
import * as IconDocOnDoc from "./components/icons/IconDocOnDoc/IconDocOnDoc.mjs";
import * as PopoverComponent from "./components/PopoverComponent/PopoverComponent.mjs";

function $$default(param) {
  var c = function (tool) {
    console.log("clicked tool " + tool);
  };
  return React.createElement("div", undefined, React.createElement(PopoverComponent.make, {
                  children: "Small content",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(PopoverComponent.make, {
                  tools: [
                    "edit",
                    "copy"
                  ],
                  clickTool: c,
                  children: "Small content with tools",
                  toolTemplates: [
                    React.createElement(IconPencil.make, {}),
                    React.createElement(IconDocOnDoc.make, {})
                  ],
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(PopoverComponent.make, {
                  children: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla libero elit, porttitor nec egestas in, congue a lorem. Suspendisse vitae dolor non tortor hendrerit rhoncus. In hac habitasse platea dictumst. Sed bibendum aliquet sollicitudin. Suspendisse luctus mauris dignissim ligula dignissim porttitor. Integer ut metus facilisis, pharetra augue et, luctus tortor. Suspendisse molestie risus lorem, quis sagittis odio venenatis vel. Donec luctus commodo dolor ut sollicitudin. Cras faucibus sit amet odio vitae tincidunt. Suspendisse potenti. Proin odio nunc, hendrerit ut est eu, finibus consectetur urna. Quisque nec tincidunt eros. Cras tincidunt, lacus ac vehicula tincidunt, massa odio accumsan sem, non venenatis tortor lorem in orci.",
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }), React.createElement(PopoverComponent.make, {
                  tools: [
                    "edit",
                    "copy"
                  ],
                  clickTool: c,
                  children: "Tools: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla libero elit, porttitor nec egestas in, congue a lorem. Suspendisse vitae dolor non tortor hendrerit rhoncus. In hac habitasse platea dictumst. Sed bibendum aliquet sollicitudin. Suspendisse luctus mauris dignissim ligula dignissim porttitor. Integer ut metus facilisis, pharetra augue et, luctus tortor. Suspendisse molestie risus lorem, quis sagittis odio venenatis vel. Donec luctus commodo dolor ut sollicitudin. Cras faucibus sit amet odio vitae tincidunt. Suspendisse potenti. Proin odio nunc, hendrerit ut est eu, finibus consectetur urna. Quisque nec tincidunt eros. Cras tincidunt, lacus ac vehicula tincidunt, massa odio accumsan sem, non venenatis tortor lorem in orci.",
                  toolTemplates: [
                    React.createElement(IconPencil.make, {}),
                    React.createElement(IconDocOnDoc.make, {})
                  ],
                  props: {
                    style: {
                      marginTop: "16px",
                      marginBottom: "16px"
                    }
                  }
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
