// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as IconPlusSmall from "./components/icons/IconPlusSmall/IconPlusSmall.mjs";
import * as TextFieldComponent from "./components/TextFieldComponent/TextFieldComponent.mjs";

function $$default(param) {
  var match = React.useState(function () {
        return "";
      });
  var setLastInput = match[1];
  var onChange = function (s) {
    Curry._1(setLastInput, (function (param) {
            return s;
          }));
  };
  return React.createElement("div", undefined, React.createElement("p", undefined, "Last input: " + match[0] + ""), React.createElement(TextFieldComponent.make, {
                  onChange: onChange,
                  children: "Title"
                }), React.createElement(TextFieldComponent.make, {
                  isError: true,
                  onChange: onChange,
                  children: "Error",
                  props: {
                    style: {
                      margin: "16px 0"
                    }
                  }
                }), React.createElement(TextFieldComponent.make, {
                  disabled: true,
                  onChange: onChange,
                  children: "Disabled",
                  props: {
                    style: {
                      margin: "16px 0"
                    }
                  }
                }), React.createElement(TextFieldComponent.make, {
                  disabled: true,
                  isError: true,
                  onChange: onChange,
                  children: "Disabled error",
                  props: {
                    style: {
                      margin: "16px 0"
                    }
                  }
                }), React.createElement(TextFieldComponent.make, {
                  forceWithContentState: true,
                  onChange: onChange,
                  children: "Force upper caption",
                  props: {
                    style: {
                      margin: "16px 0"
                    }
                  }
                }), React.createElement(TextFieldComponent.make, {
                  onChange: onChange,
                  contentSlot: Caml_option.some(React.createElement(IconPlusSmall.make, {})),
                  children: "With content",
                  props: {
                    style: {
                      margin: "16px 0"
                    }
                  }
                }), React.createElement(TextFieldComponent.make, {
                  autoselect: true,
                  onChange: onChange,
                  children: "Autoselect",
                  props: {
                    style: {
                      margin: "16px 0"
                    }
                  }
                }), React.createElement(TextFieldComponent.make, {
                  autofocus: true,
                  onChange: onChange,
                  children: "Autofocus",
                  props: {
                    style: {
                      margin: "16px 0"
                    }
                  }
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
