// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function MainLayout$Navigation(props) {
  return React.createElement("nav", undefined, React.createElement(Link, {
                  href: "/",
                  children: null
                }, React.createElement("img", {
                      src: "/static/zeit-black-triangle.svg"
                    }), React.createElement("span", undefined, "Next", React.createElement("span", undefined, " + ReScript"))), React.createElement("div", undefined, React.createElement(Link, {
                      href: "/",
                      children: "Home"
                    }), React.createElement(Link, {
                      href: "/examples",
                      children: "Examples"
                    }), React.createElement("a", {
                      href: "https://github.com/ryyppy/nextjs-default",
                      target: "_blank"
                    }, "Github")));
}

function MainLayout(props) {
  var minWidth = {
    minWidth: "20rem"
  };
  return React.createElement("div", {
              style: minWidth
            }, React.createElement("div", undefined, React.createElement(MainLayout$Navigation, {}), React.createElement("main", undefined, props.children)));
}

var make = MainLayout;

export {
  make ,
}
/* react Not a pure module */
